#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    countNeg =0
    countPos =0
    countZero =0
    n = len(arr)
    for i in arr:
        if i == 0:
            countZero +=1
        elif i > 0:
            countPos +=1
        else:
            countNeg +=1
    return (countPos/n , countNeg/n , countZero/n)
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    posRatio, negRatio, zeroRatio = plusMinus(arr)
    print(f"{posRatio:.6f}")
    print(f"{negRatio:.6f}")
    print(f"{zeroRatio:.6f}")
    
    
